# Generated by Django 3.1.7 on 2021-03-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wishlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.wishlist'),
            preserve_default=False,
        ),
    ]
